### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by wamuyu-felix** [hcbpassos/double_back_to_close_app#17]
I am getting this error when a try installing the latest this package as described [here](https://pub.dev/packages/double_back_to_close_app/install).

Because myapp depends on double_back_to_close_app >=1.3.0-nullsafety.1 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
pub get failed (1; Because myapp depends on double_back_to_close_app >=1.3.0-nullsafety.1 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)
exit code 1

I have already upgraded to the latest version of the flutter SDK.

Running flutter doctor returns this

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.17763.107], locale en-KE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

Running flutter --version returns

Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (3 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

**Comment by mdanialr** [comment]
@King7Ace i ever bumped to this kind of error in Deepin 20. I change my channel to dev or master with `flutter channel dev` and its worked for me.

**Comment by hcbpassos** [comment]
sorry for the late response. i accidentally disabled my email notifications.

the latest version of this package requires dart >= 2.12.0-0, but yours is dart 2.10.4. please try @mdanialr suggestion and switch to a different channel.
