### ISSUE TITLE
what about this..

### ISSUE THREAD

**Issue by bakboem** [hcbpassos/double_back_to_close_app#19]
WillPopScope(
        onWillPop: () async {
          if (exitAppTimer == null) {
            exitAppTimer = Timer(Duration(seconds: 3), () {});
            AppToast().show(context, '${tr('ext_app_when_tap_again')}');
          } else {
            if (exitAppTimer!.isActive) {
              exit(0);
            } else {
              exitAppTimer = Timer(Duration(seconds: 3), () {});
              AppToast().show(context, '${tr('ext_app_when_tap_again')}');
            }
          }

          return false;
        },

**Comment by hcbpassos** [comment]
thanks for the suggestion ❤️  also, sorry for the late response. i accidentally disabled my email notifications.

this solution has a few downsides, though. for instance, it won't check `ModalRoute.willHandlePopInternally`, so if a drawer is open, it won't close before showing the toast.
