### ISSUE TITLE
App ask for double-tap to close the drawer when it's opened

### ISSUE THREAD

**Issue by alyyasser** [hcbpassos/double_back_to_close_app#4]
it should ignore (or add more check) the double-tap behaviour when navigation drawer is opened.

**Comment by ghost** [comment]
If the drawer is open and the back-button gets pressed, `DoubleBackToCloseApp`'s `WillPopScope` should not even fire `onWillPop`. 

I'll investigate that.

Thanks for your issue.

**Comment by alyyasser** [comment]
it'll trigger `onWillPop`, because, to close the drawer, it actually used `Navigator.pop(context)`.

i've tried using these code:
```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: buildAppBar(),
      drawer: buildDrawer(),
      body: DoubleBackToCloseApp(
        snackBar: SnackBar(
          content: Text('Tap back again to leave'),
        ),
        child: buildBody(),
      ),
    );
  }
```
and
```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DoubleBackToCloseApp(
        snackBar: SnackBar(
          content: Text('Tap back again to leave'),
        ),
        child: Scaffold(
          appBar: buildAppBar(),
          drawer: buildDrawer(),
          body: buildBody(),
        ),
      ),
    );
  }
```

both trigger the same issue.

**Comment by ghost** [comment]
> it'll trigger onWillPop, because, to close the drawer, it actually used Navigator.pop(context).

This is why I expected `onWillPop` to not fire. Since you can close the drawer with `Navigator.pop()`, it behaves similarly to a route, and `DoubleBackToCloseApp`'s `onWillPop` fires only when you are in its route, and doesn't when you are in any other route.

If you open a `PopupMenu`, for example, `onWillPop` won't fire on back-button, because `PopupMenu` actually opens another route:

```dart
import 'package:double_back_to_close_app/double_back_to_close_app.dart';
import 'package:flutter/material.dart';

void main() => runApp(Example());

class Example extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          actions: [
            PopupMenuButton<int>(
              itemBuilder: (context) => [
                const PopupMenuItem(
                  value: 0,
                  child: Text('Item 0'),
                ),
              ],
            )
          ],
        ),
        body: DoubleBackToCloseApp(
          snackBar: const SnackBar(
            content: Text('Tap back again to leave'),
          ),
          child: Center(
            child: OutlineButton(
              child: Text('Tap to simulate back'),
              onPressed: WidgetsBinding.instance.handlePopRoute,
            ),
          ),
        ),
      ),
    );
  }
}
```

Ends up that the drawer doesn't create another route. It creates a `LocalHistoryEntry`, instead.

I'm investigating how to deal with that.

**Comment by ghost** [comment]
Found a solution that handles all cases where a new `LocalHistoryEntry` is inserted. Should land soon.

Thank you very much for spotting this problem.
