### ISSUE TITLE
NoSuchMethodError: The getter 'pressback' was called on null

### ISSUE THREAD

**Issue by AlecSPb** [hcbpassos/double_back_to_close_app#8]
My code:
![image](https://user-images.githubusercontent.com/10573184/77356073-b042bc00-6d56-11ea-9af5-38dc38d9b00a.png)
My screen:
![image](https://user-images.githubusercontent.com/10573184/77356659-cb61fb80-6d57-11ea-8e1f-efdda942c5c9.png)

When I write the code: `content: Text ("Press back again to exit",),` that works.
How do you use this in your application locales?

**Comment by ghost** [comment]
`I18n.of(context)` returns `null`, so I cannot see how this package influences in this error. As such, if you remove `DoubleBackToCloseApp`, the error should remain. Try this:

```dart
body: Center(
  child: Text(I18n.of(context).pressback),
),
```

Probably there's something wrong about your `i18n` set up :)

**Comment by AlecSPb** [comment]
```Dart
body: Center(
  child: Text(I18n.of(context).pressback),
),
```
This code is't work.
I also tried the Intl plugin. The same error crashes
```Dart
body: Center(
    child: Text(S.of(context).homeScreenDoubleBackToCloseAppSnackBarText)),
```

**Comment by ghost** [comment]
> This code is't work.

As expected. Therefore, your issue is not related to `DoubleBackToCloseApp`.

Please check your internationalization set up.
